apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
 
  selector:
    app: postgress
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgress
spec:
  selector:
   # replicas: 5
    matchLabels:
      app: postgress
  template:
    metadata:
      labels:
        app: postgress
    spec:
      containers:
      - name: postgress
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgress-configmap
              key: postgres-db
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgress-configmap
              key: postgres_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: postgress-configmap
              key: postgres_pass
        ports:
        - containerPort: 5432
       

