apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  #replicas: 5
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: divyadockerhub1998/kubernetes-ui
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  selector:
    app: ui
  type: NodePort
  ports:
    - nodePort: 31111
      port: 80
      targetPort: 80

